### Add a New Post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My  check demo Post",
  "content": "This is the content of post for demo",
  "senderId": "1235",
  "owner": "demo"  
}

### Get All Posts
GET http://localhost:3000/posts/getposts
###Get post by Id
GET http://localhost:3000/posts/6766bb2c08142b4db5c51934
###Get post by sender Id
GET http://localhost:3000/posts?senderId=1235

### Update Post
PUT http://localhost:3000/posts/67406927fbde634430a5db31
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "This is the updated content of the post.",
  "senderId": "1234",
  "owner": "demo"
}
### Create a comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "comment": "this is new comment for demo",
  "postId": "67406927fbde634430a5db31",
  "owner": "demo"
}
### Get all comments
GET http://localhost:3000/comments/getcomments

### Get a specific comment by its ID
GET http://localhost:3000/comments/674074c69b8f39e158b05242

### Update a specific comment by its ID
PUT http://localhost:3000/comments/674074c69b8f39e158b05242
Content-Type: application/json

{
  "comment": "this is update comment for demo",
  "postId": "67406927fbde634430a5db31",
  "owner": "demo"
}
### Delete a specific comment by its ID
DELETE http://localhost:3000/comments/674074c69b8f39e158b05242


